// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:515764383172:web:67f628f9d1a24b3c684891',
    messagingSenderId: '515764383172',
    projectId: 'smartchef-fc092',
    authDomain: 'smartchef-fc092.firebaseapp.com',
    storageBucket: 'smartchef-fc092.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:515764383172:android:45cecd974a414b57684891',
    messagingSenderId: '515764383172',
    projectId: 'smartchef-fc092',
    storageBucket: 'smartchef-fc092.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:515764383172:ios:66f348ef3a8d6c9f684891',
    messagingSenderId: '515764383172',
    projectId: 'smartchef-fc092',
    storageBucket: 'smartchef-fc092.firebasestorage.app',
    iosBundleId: 'com.example.smartchef',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ?? '',
    appId: '1:515764383172:ios:66f348ef3a8d6c9f684891',
    messagingSenderId: '515764383172',
    projectId: 'smartchef-fc092',
    storageBucket: 'smartchef-fc092.firebasestorage.app',
    iosBundleId: 'com.example.smartchef',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? '',
    appId: '1:515764383172:web:e8e110227e8016c4684891',
    messagingSenderId: '515764383172',
    projectId: 'smartchef-fc092',
    authDomain: 'smartchef-fc092.firebaseapp.com',
    storageBucket: 'smartchef-fc092.firebasestorage.app',
  );
}
